module.exports={
    Admin_Credentials:"admin",
    Category_Details:"category",
    Product_Details:"product",
    Brand_Details:"brand",
    User_Details:"users",
    User_Cart:"usercart",
    Order_List:"order",
    Whish_List:"whishlist",
    Banner_Details:"banner",
    Coupon_Details:"coupon",
    User_Address:"address"
}